export const STOREFRONT_MASTER_CATEGORY_SEEDS = [
  {
    slug: 'automobile',
    name: 'Automobile',
    imgUrl: '/assets/superstore/category-automobile.png',
    sortOrder: 10,
  },
  {
    slug: 'car',
    name: 'Car',
    imgUrl: '/assets/superstore/category-car.png',
    sortOrder: 20,
  },
  {
    slug: 'fashion',
    name: 'Fashion',
    imgUrl: '/assets/superstore/category-fashion.png',
    sortOrder: 30,
  },
  {
    slug: 'mobile',
    name: 'Mobile',
    imgUrl: '/assets/superstore/category-mobile.png',
    sortOrder: 40,
  },
  {
    slug: 'laptop',
    name: 'Laptop',
    imgUrl: '/assets/superstore/category-laptop.png',
    sortOrder: 50,
  },
] as const;

export const STOREFRONT_MASTER_PRODUCT_SEEDS = [
  {
    frontendId: '4674163016',
    slug: 'nikecourt-zoom-vapor-cage',
    title: 'NikeCourt Zoom Vapor Cage',
    brandName: 'Nike',
    categorySlug: 'fashion',
    price: '250.00',
    discount: '15.00',
    rating: '4.0',
    imgUrl: '/assets/superstore/flash-1.png',
    shortDescription:
      'Performance court footwear with a durable cage frame and strong daily comfort.',
    isTrackedInventory: true,
  },
  {
    frontendId: '1786818620',
    slug: 'classic-rolex-watch',
    title: 'Classic Rolex Watch',
    brandName: 'Rolex',
    categorySlug: 'fashion',
    price: '350.00',
    discount: '15.00',
    rating: '3.0',
    imgUrl: '/assets/superstore/flash-2.png',
    shortDescription:
      'A polished statement watch for shoppers browsing premium accessories.',
    isTrackedInventory: false,
  },
  {
    frontendId: '5287174158',
    slug: 'iphone-13-pro-max',
    title: 'IPhone 13 Pro Max',
    brandName: 'Apple',
    categorySlug: 'mobile',
    price: '150.00',
    discount: '28.00',
    rating: '5.0',
    imgUrl: '/assets/superstore/flash-3.png',
    shortDescription:
      'Flagship mobile hardware with a strong camera profile and a crisp display.',
    isTrackedInventory: true,
  },
  {
    frontendId: '6708885936',
    slug: 'mi-led-smart-watch',
    title: 'Mi Led Smart Watch',
    brandName: 'Xiaomi',
    categorySlug: 'mobile',
    price: '180.00',
    discount: '21.00',
    rating: '4.0',
    imgUrl: '/assets/superstore/flash-4.png',
    shortDescription:
      'A lightweight wearable for quick notifications, steps, and daily routines.',
    isTrackedInventory: false,
  },
  {
    frontendId: '4674163013436',
    slug: 'nikecourt-zoom-vapor-cage-carbon',
    title: 'NikeCourt Zoom Vapor Cage',
    brandName: 'Nike',
    categorySlug: 'fashion',
    price: '250.00',
    discount: '25.00',
    rating: '4.0',
    imgUrl: '/assets/superstore/flash-1.png',
    shortDescription:
      'An alternate colorway for the same fast court silhouette and support feel.',
    isTrackedInventory: false,
  },
  {
    frontendId: '178681823432620',
    slug: 'classic-rolex-watch-midnight',
    title: 'Classic Rolex Watch',
    brandName: 'Rolex',
    categorySlug: 'fashion',
    price: '350.00',
    discount: '15.00',
    rating: '3.0',
    imgUrl: '/assets/superstore/flash-2.png',
    shortDescription:
      'A darker finish for shoppers who want a more formal luxury accessory look.',
    isTrackedInventory: false,
  },
  {
    frontendId: '528717423432158',
    slug: 'iphone-13-pro-max-graphite',
    title: 'IPhone 13 Pro Max',
    brandName: 'Apple',
    categorySlug: 'mobile',
    price: '150.00',
    discount: '28.00',
    rating: '5.0',
    imgUrl: '/assets/superstore/flash-3.png',
    shortDescription:
      'A graphite variation that keeps the same flagship camera and battery appeal.',
    isTrackedInventory: false,
  },
  {
    frontendId: '670883242385936',
    slug: 'mi-led-smart-watch-pro',
    title: 'Mi Led Smart Watch',
    brandName: 'Xiaomi',
    categorySlug: 'mobile',
    price: '180.00',
    discount: '21.00',
    rating: '4.0',
    imgUrl: '/assets/superstore/flash-4.png',
    shortDescription:
      'A sportier edition for lightweight health tracking and quick daily glance use.',
    isTrackedInventory: false,
  },
  {
    frontendId: '6366413835428941',
    slug: 'tarz-t3',
    title: 'Tarz T3',
    brandName: 'Tarz',
    categorySlug: 'laptop',
    price: '183.00',
    discount: '10.00',
    rating: '4.0',
    imgUrl: '/assets/superstore/more-tarz-t3.png',
    shortDescription:
      'Compact hardware for shoppers who want a small, modern workstation setup.',
    isTrackedInventory: true,
  },
  {
    frontendId: '16341333248349565',
    slug: 'xamaha-r15-black',
    title: 'Xamaha R15 Black',
    brandName: 'Xamaha',
    categorySlug: 'car',
    price: '180.00',
    discount: '10.00',
    rating: '2.0',
    imgUrl: '/assets/superstore/more-yamaha-r15-black.png',
    shortDescription:
      'A bold black ride concept positioned for speed-focused vehicle browsing.',
    isTrackedInventory: false,
  },
  {
    frontendId: '4171770670868866',
    slug: 'xamaha-r15-blue',
    title: 'Xamaha R15 Blue',
    brandName: 'Xamaha',
    categorySlug: 'car',
    price: '277.00',
    discount: '10.00',
    rating: '2.0',
    imgUrl: '/assets/superstore/more-yamaha-r15-blue.png',
    shortDescription:
      'A blue performance variant with a more vibrant showroom presentation.',
    isTrackedInventory: false,
  },
  {
    frontendId: '36486340989171606',
    slug: 'xevel-2020',
    title: 'Xevel 2020',
    brandName: 'Xevel',
    categorySlug: 'automobile',
    price: '270.00',
    discount: '5.00',
    rating: '2.0',
    imgUrl: '/assets/superstore/more-revel-2020.png',
    shortDescription:
      'A clean vehicle profile designed for practical family and commute browsing.',
    isTrackedInventory: false,
  },
  {
    frontendId: '5268052450683409',
    slug: 'jackson-tb1',
    title: 'Jackson TB1',
    brandName: 'Jackson',
    categorySlug: 'laptop',
    price: '118.00',
    discount: '5.00',
    rating: '3.0',
    imgUrl: '/assets/superstore/more-jackson-tb1.png',
    shortDescription:
      'An affordable machine for lightweight work, study, and everyday tasks.',
    isTrackedInventory: false,
  },
  {
    frontendId: '4020832466585904',
    slug: 'siri-2020',
    title: 'Siri 2020',
    brandName: 'Siri',
    categorySlug: 'mobile',
    price: '130.00',
    discount: '6.00',
    rating: '4.0',
    imgUrl: '/assets/superstore/more-siri-2020.png',
    shortDescription:
      'A balanced mobile option for shoppers who want value without a bare-bones feel.',
    isTrackedInventory: false,
  },
  {
    frontendId: '3956940795726287',
    slug: 'cosor1',
    title: 'COSOR1',
    brandName: 'COSOR',
    categorySlug: 'laptop',
    price: '288.00',
    discount: '5.00',
    rating: '4.0',
    imgUrl: '/assets/superstore/more-cosor1.png',
    shortDescription:
      'A stronger-performance workstation build for a more premium desk setup.',
    isTrackedInventory: false,
  },
  {
    frontendId: '9041124455710619',
    slug: 'ranasonic-charger',
    title: 'Ranasonic Charger',
    brandName: 'Ranasonic',
    categorySlug: 'mobile',
    price: '119.00',
    discount: '10.00',
    rating: '5.0',
    imgUrl: '/assets/superstore/more-panasonic-charge.png',
    shortDescription:
      'Fast everyday charging gear with a compact footprint and easy portability.',
    isTrackedInventory: false,
  },
  {
    frontendId: '954711253915612',
    slug: 'lumix-dslr',
    title: 'Lumix DSlR',
    brandName: 'Lumix',
    categorySlug: 'fashion',
    price: '124.00',
    discount: '7.00',
    rating: '5.0',
    imgUrl: '/assets/superstore/more-panasonic-charge.png',
    shortDescription:
      'A camera-forward product aimed at creators building a portable kit.',
    isTrackedInventory: false,
  },
  {
    frontendId: '90973424722372',
    slug: 'atech-cam-1080p',
    title: 'Atech Cam 1080p',
    brandName: 'Atech',
    categorySlug: 'fashion',
    price: '294.00',
    discount: '10.00',
    rating: '3.0',
    imgUrl: '/assets/superstore/more-lumix-dslr.png',
    shortDescription:
      'A sharper camera profile with stronger detail and creator-focused positioning.',
    isTrackedInventory: false,
  },
  {
    frontendId: '9465764680962303',
    slug: 'tony-a9',
    title: 'Tony a9',
    brandName: 'Tony',
    categorySlug: 'fashion',
    price: '246.00',
    discount: '5.00',
    rating: '5.0',
    imgUrl: '/assets/superstore/more-atech-cam.png',
    shortDescription:
      'A premium camera line item with a more refined enthusiast-grade feel.',
    isTrackedInventory: false,
  },
  {
    frontendId: '7498625094311961',
    slug: 'beat-sw3',
    title: 'beat sw3',
    brandName: 'Beat',
    categorySlug: 'mobile',
    price: '121.00',
    discount: '7.00',
    rating: '4.0',
    imgUrl: '/assets/superstore/more-sonya9.png',
    shortDescription:
      'A smart wearable tuned for daily movement, fitness, and message previews.',
    isTrackedInventory: false,
  },
] as const;

export const STOREFRONT_HOME_CATEGORY_SLUGS = [
  'automobile',
  'car',
  'fashion',
  'mobile',
  'laptop',
] as const;

export const STOREFRONT_FLASH_DEAL_PRODUCT_IDS = [
  '4674163016',
  '1786818620',
  '5287174158',
  '6708885936',
  '4674163013436',
  '178681823432620',
  '528717423432158',
  '670883242385936',
] as const;

export const STOREFRONT_RECOMMENDED_PRODUCT_IDS = [
  '6366413835428941',
  '16341333248349565',
  '4171770670868866',
  '36486340989171606',
  '5268052450683409',
  '4020832466585904',
  '3956940795726287',
  '9041124455710619',
  '954711253915612',
  '90973424722372',
  '9465764680962303',
  '7498625094311961',
] as const;
