export enum FulfillmentStatus {
  PENDING = 'PENDING',
  READY_FOR_SHIPMENT = 'READY_FOR_SHIPMENT',
  HANDED_OVER = 'HANDED_OVER',
  DELIVERED = 'DELIVERED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  RETURNED = 'RETURNED',
}
