export enum InventoryTransactionType {
  RESERVE = 'RESERVE',
  COMMIT = 'COMMIT',
  RELEASE = 'RELEASE',
  RESTORE = 'RESTORE',
  MANUAL_ADD = 'MANUAL_ADD',
  MANUAL_REMOVE = 'MANUAL_REMOVE',
  RETURN_RESTOCK = 'RETURN_RESTOCK',
}
